### ISSUE TITLE
Javadoc warnings and errors on generated code

### ISSUE THREAD

**Issue by agentgt** [avaje/avaje-prisms#12]
Yes obviously it is a dumb idea to rely on generated code javadoc but ideally the generated code has valid javadoc.

Currently I just exclude the prisms package but ideally the generated code does not produce any warnings or errors on missing tags:

```
warning: no @param for element
[ERROR]     public static boolean isPresent(Element element) {
```

If @SentryMan doesn't have time I can probably fix this this weekend as I most likely will switch to using this library instead of pistachio.

**Comment by SentryMan** [comment]
nah I got it

**Comment by SentryMan** [comment]
so how do you reproduce? Where does this error come from, the javadoc plugin?

**Comment by agentgt** [comment]
Actually the only real error ignoring warnings is:

```
[ERROR] /jstachio/compiler/jstachio-prisms/target/generated-sources/annotations/io/jstach/apt/prism/JStacheConfigPrism.java:172: error: unknown tag: JStacheNamePrism
[ERROR]       * Returns a List<JStacheNamePrism> representing the value of the {@code naming()} member of the Annotation.
```

**Comment by agentgt** [comment]
... I did that PR online aka via github website... so you know it might not be complete.

**Comment by SentryMan** [comment]
> I can't test as I don't have access ATM to a windows machine.

Got both a Macbook and Windows and it doesn't seem to fail.
 also a brief look on SO says that it's good? https://stackoverflow.com/questions/1883345/whats-up-with-javas-n-in-printf

even so I can update

**Comment by agentgt** [comment]
It is not that it won't fail it is that it makes the build not reproducible.

If you build on a windows machine the output will be different.

**Comment by agentgt** [comment]
Here is the commit I adjusted the javadoc on pistachio.

https://github.com/jstachio/pistachio/commit/1d6506684ff76be218b3a7a5feaf94c4b8d94b5a

It might help you but probably not.

**Comment by SentryMan** [comment]
Changes are deployed
